<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5.0;net6.0;net7.0;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>SimpLog.FileLog</PackageId>
    <Version>1.0.4</Version>
    <Authors>Georgi Chekanov</Authors>
    <Company>Georgi Chekanov</Company>
    <Product>SimpLog</Product>
    <Description>SimpLog.FileLog provides lightweight, configurable file logging for .NET apps with multiple log levels and optional buffered writes.</Description>
    <Copyright>Copyright (c) Georgi Chekanov 2025</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>logging file-logging logger logs dotnet async lightweight simple</PackageTags>
    <PackageReleaseNotes>- optimised the library
- OS independent</PackageReleaseNotes>
    <PackAsTool>False</PackAsTool>
    <ToolCommandName>simplog-filelog</ToolCommandName>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/simplog-project/SimpLog.FileLog</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Samples\" />
  </ItemGroup>

</Project>
